# Generated by Django 4.2.7 on 2025-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Имя автора"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=128, verbose_name="Страна"),
                ),
                (
                    "birth_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год рождения"
                    ),
                ),
                (
                    "death_year",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Год смерти"
                    ),
                ),
                ("about", models.TextField(blank=True, verbose_name="О авторе")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
                "ordering": ["name"],
            },
        ),
    ]
