# Generated by Django 4.2.7 on 2025-10-19 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_merge_0004_0005"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="subscription_until",
        ),
    ]
