# Generated by Django 4.2.7 on 2025-10-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_profile_subscription_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="Подписка действует до"
            ),
        ),
    ]
