# Generated by Django 4.2.7 on 2025-10-17 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="books_title_7a737c_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["author"], name="books_author_1c43f5_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["genre"], name="books_genre_d6e4af_idx"),
        ),
    ]
