# Generated by Django 4.2.7 on 2025-10-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_fix_added_by_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="preview_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
