# Generated by Django 4.2.7 on 2025-10-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_preview_text_alter_book_cover_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="preview_text",
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.FloatField(default=3.5),
        ),
        migrations.DeleteModel(
            name="Loan",
        ),
    ]
