# Generated by Django 4.2.7 on 2025-10-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_fill_slugs_and_make_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ("title",),
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="books_title_7a737c_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="books_author_1c43f5_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="books_genre_d6e4af_idx",
        ),
        migrations.RemoveField(
            model_name="book",
            name="added_by",
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=255, verbose_name="Автор"),
        ),
        migrations.AlterField(
            model_name="book",
            name="available_copies",
            field=models.PositiveIntegerField(default=1, verbose_name="Доступно"),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True, null=True, verbose_name="URL обложки"),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("FANTASY", "Фэнтези"),
                    ("SCIFI", "Научная фантастика"),
                    ("MYSTERY", "Детектив"),
                    ("ROMANCE", "Роман"),
                    ("TECH", "Технологии"),
                    ("HISTORY", "История"),
                    ("OTHER", "Другое"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Доступна для выдачи"),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=32, verbose_name="ISBN"),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Год издания"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=3, verbose_name="Рейтинг"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="book",
            name="total_copies",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Всего экземпляров"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
        ),
        migrations.AlterModelTable(
            name="book",
            table=None,
        ),
    ]
