# Generated by Django 4.2.7 on 2025-10-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("sci_fi", "Научная фантастика"),
                    ("romance", "Роман"),
                    ("history", "История"),
                    ("cs", "Программирование"),
                    ("science", "Наука"),
                    ("detective", "Детектив"),
                    ("poetry", "Поэзия"),
                    ("other", "Другое"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="Жанр",
            ),
        ),
    ]
