# Generated by Django 4.2.7 on 2025-10-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="loan",
            name="loans_status_9049a0_idx",
        ),
        migrations.RemoveIndex(
            model_name="loan",
            name="loans_due_dat_3e4b70_idx",
        ),
        migrations.AlterField(
            model_name="loan",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="loan_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="return_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("BORROWED", "Выдана"),
                    ("RETURNED", "Возвращена"),
                    ("OVERDUE", "Просрочена"),
                ],
                default="BORROWED",
                max_length=10,
            ),
        ),
        migrations.AlterModelTable(
            name="loan",
            table="loans_loan",
        ),
    ]
