# Generated by Django 4.2.7 on 2025-10-18 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0002_alter_loan_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="loan_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("returned", "Returned"),
                    ("overdue", "Overdue"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="loan",
            table=None,
        ),
    ]
