# Generated by Django 4.2.7 on 2025-10-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0003_alter_loan_loan_date_alter_loan_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loan",
            options={"ordering": ("-loan_date",)},
        ),
        migrations.AlterField(
            model_name="loan",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активен"), ("RETURNED", "Закрыт")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["user", "book"], name="loans_loan_user_id_d714f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["status"], name="loans_loan_status_962e99_idx"),
        ),
    ]
